name: Modify Repo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  modify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Winlator-App
        uses: actions/checkout@v4
        with:
          repository: DarkCode2317/winlator-app
          path: winlator

      - name: Copy gradle
        run: |
          cp -r winlator/gradle .
          cp winlator/gradlew .
          cp winlator/build.gradle .
          cp winlator/settings.gradle .
          cp winlator/gradle.properties .
          rm -rf winlator

      - name: Commit
        run: |
          git config user.name "DarkCode2317"
          git config user.email "darkcode2317@gmail.com"
          git add .
          git commit -m "Modify repo"
          git push origin HEAD:vanilla --force